/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RequestMapping;

import com.example.business.exception.InvalidRequestException;
import com.example.business.exception.NoSuchUserException;
import com.example.business.exception.UserAlreadyExistsException;

@Controller
public class HomeController {
    @RequestMapping("/")
    public String sayHello(Model model) {
        model.addAttribute("name", "Yaffa");
        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/getUser")
    public String getUser() throws NoSuchUserException {
        
        throw new NoSuchUserException();
    }    

    // ExceptionHandlerExceptionResolver
    @ExceptionHandler
    public String noSuchUserHandler(NoSuchUserException e) {
        return "no-such-user";

    }

    // ResponseStatusExceptionResolver
    @RequestMapping("/addUser")
    public String addUser() throws UserAlreadyExistsException {
        throw new UserAlreadyExistsException();
    }

    // ResponseStatusExceptionResolver
    @RequestMapping("/updateUser")
    public String updateUser() throws InvalidRequestException {
        throw new InvalidRequestException();
    }
   
}