/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.bind.annotation.ExceptionHandler;

import com.example.business.exception.*;

@Controller
public class HomeController {
    @RequestMapping("/")
    public String sayHello(Model model) {
        model.addAttribute("name", "Yaffa");
        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/getUser")
    public String getUser() throws NoSuchUserException {
        
        throw new NoSuchUserException();
    }    

    // ExceptionHandlerExceptionResolver
    @ExceptionHandler
    public ModelAndView noSuchUserHandler(NoSuchUserException e) {
        ModelAndView modelAndView = new ModelAndView();
        modelAndView.setViewName("no-such-user");
        return modelAndView;

    }

    // ResponseStatusExceptionResolver
    @RequestMapping("/addUser")
    public String addUser() throws UserAlreadyExistsException {
        throw new UserAlreadyExistsException();
    }

    // ResponseStatusExceptionResolver
    @RequestMapping("/updateUser")
    public String updateUser() throws InvalidRequestException {
        throw new InvalidRequestException();
    }
   
}