/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Statement;

import javax.sql.DataSource;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.mysql.cj.jdbc.MysqlDataSource;

public class App {

    public static DataSource createConnection() {
        String dbUrl = "jdbc:mysql://localhost:3306/users";
        String dbUser = "yoav";
        String dbPassword = "yoav";

        MysqlDataSource mysqlDS = null;
        
        mysqlDS = new MysqlDataSource();
        mysqlDS.setURL(dbUrl);
        mysqlDS.setUser(dbUser);
        mysqlDS.setPassword(dbPassword);

        return mysqlDS;
        
    }

    public static void main(String[] args)  {
        
        // we create the connection using the DriverManager.getConnection
        try(Connection conn = createConnection().getConnection()) {

            // we can check if the connection is good
            System.out.println("isValid: " + conn.isValid(0));
            
            // we want to create statement in a try clause because we need to release it after using it.
            try(Statement stmt = conn.createStatement()) {
                ResultSet rs = stmt.executeQuery("select * from users");
                while(rs.next()) {
                    System.out.println(rs.getInt(1) + "  " + rs.getString(2));  
                }
            }
            
            // PrepareadStatement is a precompiled statement in which you can embed values
            // this is usually how you embed user-entered data to SQL statements
            String insertStatement = "insert into USERS values (?, ?)";
            try(PreparedStatement stmt = conn.prepareStatement(insertStatement)) {
                stmt.setInt(1, 3);
                stmt.setString(2, "Tamar");

                int rowsAffected = stmt.executeUpdate();
                System.out.println("Rows affected: " + rowsAffected);
            }


        } catch(SQLException e) {
            System.out.println("SQL Exception!");
            System.out.println(e);
        }
    }
}
