/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import java.util.stream.Collectors;

import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class HomeController {
    @RequestMapping("/")
    public String sayHello(Model model) {
        model.addAttribute("name", "Yoav");
        return "index"; // This corresponds to the view name
    }

    @GetMapping("/messages")
    public ResponseEntity<Map<String, String>> getMessages(Locale locale) throws IOException {
        ClassPathResource messageFile = new ClassPathResource(String.format("Messages_%s.properties", locale.getLanguage()));
        Properties properties = new Properties();
        
        try (InputStream inputStream = messageFile.getInputStream()) {
            properties.load(new InputStreamReader(inputStream, StandardCharsets.UTF_8));
        }

        Map<String, String> m = properties.entrySet()
                .stream()
                .collect(Collectors.toMap(
                        e -> e.getKey().toString(),
                        e -> e.getValue().toString()
                ));

        return new ResponseEntity<>(m, HttpStatus.OK);
    }
   
}