/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import org.springframework.beans.BeanWrapperImpl;
import org.springframework.beans.BeanWrapper;
import java.beans.PropertyEditorManager;

public class App {
    
    public static void main(String[] args) {
        
        String classpath = System.getProperty("java.class.path");
        System.out.println(classpath);

        ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");
        BeanWrapper company = new BeanWrapperImpl(new Company());
        // setting the company name..
        company.setPropertyValue("name", "Some Company Inc.");
        // ... can also be done like this:
        //PropertyValue value = new PropertyValue("name", "Some Company Inc.");
        //company.setPropertyValue(value);

        // ok, let's create the director and tie it to the company:
        BeanWrapper jim = new BeanWrapperImpl(new Employee());
        jim.setPropertyValue("name", "Jim Stravinsky");
        company.setPropertyValue("managingDirector", jim.getWrappedInstance());

        // retrieving the salary of the managingDirector through the company
        Float salary = (Float) company.getPropertyValue("managingDirector.salary");
    }
}
