/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

import com.mysql.cj.jdbc.MysqlDataSource;

public class App {

    public static DataSource createDataSource() {
        String dbUrl = "jdbc:mysql://localhost:3306/users";
        String dbUser = "yoav";
        String dbPassword = "yoav";

        MysqlDataSource mysqlDS = null;
        
        mysqlDS = new MysqlDataSource();
        mysqlDS.setURL(dbUrl);
        mysqlDS.setUser(dbUser);
        mysqlDS.setPassword(dbPassword);

        return mysqlDS;
        
    }

    public static void main(String[] args)  {
        try(Connection conn = createDataSource().getConnection()) {

            conn.setAutoCommit(false);

            try(Statement stmt = conn.createStatement()) {
                stmt.addBatch("INSERT INTO users VALUES(4, 'John')");
                stmt.addBatch("INSERT INTO users VALUES(5, 'Kim')");
                stmt.addBatch("INSERT INTO users VALUES(6, 'Ben')");

                int[] updateCounts = stmt.executeBatch();
                conn.commit();
            }




        } catch(SQLException e) {
            System.out.println("SQL Exception!");
            System.out.println(e);
        }
    }
}
