/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import java.util.Set;
import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ModelAttribute;

import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;


@Controller
public class MyController {


    @RequestMapping("/")
    public String home(Model model) {
        DivisionDto dto = new DivisionDto();

        Division d1 = new Division();
        d1.addPerson(new Person());
        d1.addPerson(new Person());
        d1.addPerson(new Person());

        Division d2 = new Division();
        d2.addPerson(new Person());
        d2.addPerson(new Person());
        d2.addPerson(new Person());
        
        dto.addDivision(d1);
        dto.addDivision(d2);
        
        model.addAttribute("dto", dto);

        return "index"; // This corresponds to the view name
    }

    @PostMapping("/division") 
    public String postPerson(@Validated @ModelAttribute("dto") DivisionDto dto, BindingResult result) {
        if(result.hasErrors()) {
            return "index";
        }
        return "divisions";
    }
}