/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import com.example.business.service.MessageService;


@Controller
public class HomeController {
    
    @Autowired
    ApplicationContext context;

    @Autowired
    MessageService messageService;

    @RequestMapping("/methodsecurity")
    public String sayHello(Model model, @AuthenticationPrincipal Object user, Authentication authentication) {
        model.addAttribute("message", messageService.getMessage());
        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/admin")
    public String adminPage(Model model, @AuthenticationPrincipal Object user, Authentication authentication) {
        
        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/management")
    public String managementPage() {
        return "index";
    }
   
}