/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.userdetails.User;

@Controller
public class HomeController {
    
    @RequestMapping("/")
    public String sayHello(Model model, @AuthenticationPrincipal User user) {
        model.addAttribute("name", user.getUsername());
        return "index"; // This corresponds to the view name
    }
   
}