/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import spring.mvc.business.UserService;

@Controller
public class MyController {

    @Autowired
    private UserService userService;
    
    @RequestMapping("/users")
    public String getAllUsers(Model model) {
        model.addAttribute("users", userService.getAllUsers());
        return "index"; // This corresponds to the view name
    }
}