/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    
    public static void main(String[] args) {
        
        ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");
        House house = (House) context.getBean("house");

        house.setColor("Red");
        
        Meal meal = (Meal) context.getBean("meal");
        meal.setWhat("Shnizel");

        House house1 = (House) context.getBean("house");
        System.out.println(house.getColor());

        Meal meal1 = (Meal) context.getBean("meal");
        System.out.println(meal1.getWhat());

    }
}
