/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

public class App {
    public static void main(String[] args)  {
        List<User> users = null;

        String dbUrl = "jdbc:mysql://localhost:3306/users";
        String dbUser = "yoav";
        String dbPassword = "yoav";
        
        // we create the connection using the DriverManager.getConnection
        UserDAO userDao = new UserDAOJDBCImpl(dbUrl, dbUser, dbPassword);

        users = userDao.getAllUsers();

        System.out.println("All users:");
        for(User user : users) {
            System.out.println("Id: " + user.getId() + " Name: " + user.getName());
        }

        System.out.println("User by ID");
        System.out.println(userDao.getUserById(1).getName());
        
        System.out.println("Deleting user");
        userDao.deleteUser(new User(3, "Matityahu"));

        System.out.println("All users:");
        for(User user : users) {
            System.out.println("Id: " + user.getId() + " Name: " + user.getName());
        }
    }
}
