/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.validation.method.MethodValidationException;
import org.springframework.validation.method.ParameterValidationResult;
import org.springframework.context.MessageSource;

public class App {

    public static void main(String[] args) {
        
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);

        MyService myService = (MyService)context.getBean("myService");
        MessageSource messageSource = (MessageSource)context.getBean("messageSource");

        // this will trigger a validation

        System.out.println("=========== SIMPLE CASE");

        try {
            myService.myValidMethod("Yehuda", 120);
        } catch(MethodValidationException e) {
            // getAllValidationResults changed in Spring 7
            List<ParameterValidationResult> parameterValidationResults = e.getAllValidationResults();
            
            // get the errors for each parameter
            parameterValidationResults.forEach(pvr -> {
                pvr.getResolvableErrors().forEach(re -> {
                    System.out.println(Arrays.toString(re.getCodes()));
                });
            });
        }
        
        // calling through a method in the class will not trigger validation, because of how AOP works
        //myService.calling();

        User user = new User();
        user.setWorking(true);
        user.setAboutMe("Its all about me!");
        user.setAge(10);

        // this will trigger a validation
        System.out.println("============= takeValidUser");
        try {
            myService.takeValidUser(user);
        } catch(MethodValidationException e) {
            // getAllValidationResults changed in Spring 7
            List<ParameterValidationResult> parameterValidationResults = e.getAllValidationResults();
            
            // get the errors for each parameter
            parameterValidationResults.forEach(parameterValidationResult -> {
                parameterValidationResult.getResolvableErrors().forEach(resolvableError -> {
                    System.out.println("==== codes");
                    System.out.println(Arrays.toString(resolvableError.getCodes()));
                    System.out.println("==== resolved");
                    System.out.println(messageSource.getMessage(resolvableError, Locale.US));
                });
            });
        }

        List<User> users = new ArrayList<>();
        users.add(user);

        System.out.println("============= takeValidUsers");
        try {
            myService.takeValidUsers(users);
        } catch(MethodValidationException e) {
            // getAllValidationResults changed in Spring 7
            List<ParameterValidationResult> parameterValidationResults = e.getAllValidationResults();
            
            // get the errors for each parameter
            parameterValidationResults.forEach(parameterValidationResult -> {
                parameterValidationResult.getResolvableErrors().forEach(resolvableError -> {
                    System.out.println("==== codes");
                    System.out.println(Arrays.toString(resolvableError.getCodes()));
                    System.out.println("==== resolved");
                    System.out.println(messageSource.getMessage(resolvableError, Locale.US));
                });
            });
        }

    }

}
