/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        Logger logger = LoggerFactory.getLogger(App.class);
        logger.info("Hello World");

        int temperature = 15;

        logger.debug("Current temperature is: {}", temperature);
    }
}
