/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import java.beans.PropertyEditorSupport;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;


import org.springframework.web.bind.WebDataBinder;

import org.springframework.validation.BindingResult;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
// import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.beans.factory.annotation.Autowired;

@Controller
public class WebController {

    @Autowired
    ProductService productService;

    @RequestMapping("/")
    public String home(Model model) {
        List<Product> allProducts = productService.getAllProducts();
        ProductCategoryDto productCategoryDto = new ProductCategoryDto();
        List<ProductCategory> productCategoryList = productCategoryDto.getProductCategories();

        allProducts.stream()
            .collect(Collectors.groupingBy(Product::getCategory))
                .forEach((k, v) -> { productCategoryList.add(new ProductCategory(k, v)); });
        
        model.addAttribute("productCategoryDto", productCategoryDto);
        
        ProductQuantityDto productQuantityDto = new ProductQuantityDto();
        model.addAttribute("productQuantityDto", productQuantityDto);

        return "index"; 
    }

    @PostMapping("/update")
    public String update(@ModelAttribute ProductQuantityDto productQuantityDto, BindingResult result) {
        if(result.hasErrors()) {
            System.out.println("ERRORRS");
            return "index";
        }
        System.out.println("==============");

        List<List<ProductQuantity>> list = productQuantityDto.getProductQuantities();
        for(List<ProductQuantity> sublist : list) {
            for(ProductQuantity pc : sublist) {
                System.out.println("productId: " + pc.getProductId() + ", quantity: " + pc.getQuantity());
            }
        }

        return "redirect:/";
    }


}