/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

  public static void main(String[] args) {

    Logger logger = LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
    logger.debug("Hello world.");

  }
}