/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        
        TestBean tb = (TestBean)context.getBean("testBean");
        tb.sayHi();

        // JVM property
        System.out.println(context.getEnvironment().getProperty("animal"));
        // Environment variable
        System.out.println(context.getEnvironment().getProperty("COLOR"));

    }
}
