/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.HttpServerErrorException;
import org.springframework.web.client.RestTemplate;

import io.micrometer.observation.ObservationRegistry;

@RestController
@SpringBootApplication
public class MyApplication {
	
	private RestTemplate restTemplate;
	private ObservationRegistry observationRegistry;
	public MyApplication(ObservationRegistry registry) {
		this.observationRegistry = registry;
		this.restTemplate = new RestTemplate();
		this.restTemplate.setObservationRegistry(observationRegistry);
	}
	

	@RequestMapping("/")
	String home() {
		return "Hello World!";
	}

	@RequestMapping("/google")
	String google() {
		String url = "https://www.google.com";
        
        String response = restTemplate.getForObject(url, String.class);
        System.out.println(response);
		
		return "Hello";
	}

	@RequestMapping("/selfDelay")
	String selfDelay() {
		String response = restTemplate.getForObject("http://localhost:8082/delay?seconds=10", String.class);
		System.out.println(response);

		return response;
	}

	// just to play with the excpetions that RestTemplate throws
	@RequestMapping("clientError")
	String clientError() {
		try {
			String response = restTemplate.getForObject("http://localhost:8082/doesnt-exist", String.class);
		} catch(HttpClientErrorException e) {
			return "Client Error it is";
		}

		return "client-error-success";
	}

	// just to play with the excpetions that RestTemplate throws
	@RequestMapping("clientErrorUncaught")
	String clientErrorUncaught() {
		try{
			String response = restTemplate.getForObject("http://localhost:8082/doesnt-exist", String.class);
		} catch(HttpClientErrorException e) {
			throw e;
		}

		return "client-error-success";
	}

	@RequestMapping("serverError")
	String serverError() {
		try {
			String response = restTemplate.getForObject("http://localhost:8082/theRealServerError", String.class);
		} catch(HttpServerErrorException e) {
			return "Server Error it is";
		}

		return "Server-error-success";
	}

	@RequestMapping("theRealServerError")
	String realServerError()  throws Exception {
		throw new Exception("my bad");
	}

	@RequestMapping("/delay")
	String delay(@RequestParam("seconds") int seconds) throws InterruptedException {
		Thread.sleep(seconds * 1000);
		return "delayed";
	}

	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}
}