/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.test.web.servlet.ResultMatcher;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import org.springframework.test.web.servlet.result.ModelResultMatchers;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ModelResultMatchers mrm = MockMvcResultMatchers.model();
        ResultMatcher matcher = mrm.attribute("name", "Yoav");

        System.out.println("END");
    }
}
