/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;


import java.util.Set;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.validation.Validator;
import org.springframework.validation.SimpleErrors;
//import jakarta.validation.Validator;
import jakarta.validation.ConstraintViolation;

public class App {
    
    public static void main(String[] args) {
        
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);

	    Validator validator = (Validator)context.getBean("validator");
        
        Person yoav = new Person();
        yoav.setAge(-3);
        yoav.setName("Yoav");
        
        /* Set<ConstraintViolation<Person>> violations = validator.validate(yoav);
        
        for (ConstraintViolation<Person> violation : violations) {
            System.out.println(violation.getMessage()); 
        }
        */
        
        SimpleErrors errors = new SimpleErrors(yoav);
        validator.validate(yoav, errors);
        
        if (errors.hasErrors()) {
            // Print out the errors
            errors.getAllErrors().forEach(error -> System.out.println(error.toString()));
        } else {
            System.out.println("Form is valid.");
        }
        
    }
}
