/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jackson;

import java.io.File;
import java.io.IOException;

import com.fasterxml.jackson.databind.ObjectMapper;

public class App {

    public static void main(String[] args) throws IOException {
        
        ObjectMapper objectMapper = new ObjectMapper();
        
        //Person avi = new Person("Avi", 23);

        SendMessageCommand messageCommand = new SendMessageCommand("Yaniv", "How are you Yaniv?");
        objectMapper.writeValue(new File("command.json"), messageCommand);
    }
}
