/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;


public class App {
    public static void main(String[] args)  {
        List<Item> items = null;
        
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);


        // we create the connection using the DriverManager.getConnection
        ItemDAO itemDao = (ItemDAO)context.getBean("itemDao");

        items = itemDao.getAllItems();

        for(Item item : items) {
            System.out.println("Name: " + item.getName() + " Quantity: " + item.getQuantity());
        }

        Item vodka = new Item("Vodka", 1, ItemCategory.ALCOHOL, QuantityType.UNIT);
        //itemDao.addItem(vodka);
        itemDao.deleteItem(vodka);


    }
}
