/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;


public class App {
    public static void main(String[] args)  {
        List<Item> items = null;

        String dbUrl = "jdbc:mysql://localhost:3306/users";
        String dbUser = "yoav";
        String dbPassword = "yoav";
        
        // we create the connection using the DriverManager.getConnection
        ItemDAO itemDao = new ItemDAOJDBCImpl(dbUrl, dbUser, dbPassword);

        items = itemDao.getAllItems();

        for(Item item : items) {
            System.out.println("Name: " + item.getName() + " Quantity: " + item.getQuantity());
        }

        Item vodka = new Item("Tomato", 5, ItemCategory.FRUITS, QuantityType.KG);
        //itemDao.addItem(vodka);
        itemDao.deleteItem(vodka);


    }
}
