/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;

import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
    
    public static void multipleConfigClasses() {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        ((ConfigurableEnvironment)context.getEnvironment()).setActiveProfiles("dev");
        context.register(DevConfig.class);
        context.register(ProdConfig.class);
        context.refresh();
    
        DataSource dataSource = (DataSource)context.getBean(DataSource.class);
        dataSource.printDataSource();
    }

    public static void oneConfigClass() {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        ((ConfigurableEnvironment)context.getEnvironment()).setActiveProfiles("prod");
        context.register(AppConfig.class);
        context.refresh();
    
        DataSource dataSource = (DataSource)context.getBean(DataSource.class);
        dataSource.printDataSource();
    }

    public static void main(String[] args) {
        multipleConfigClasses();
    }
}
