/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

public class App {

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        
        TestBean tb = (TestBean)context.getBean("testBean");
        ThreadPoolTaskExecutor executor = (ThreadPoolTaskExecutor)context.getBean("taskExecutor");

        tb.sayHi();

        executor.shutdown();

        System.out.println("MAIN END");
    }
}
