/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.beans.PropertyEditorManager;

public class App {
    
    public static void main(String[] args) {
        
        ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");
        HelloWorld obj = (HelloWorld) context.getBean("helloWorld");
        obj.getMessage();

        Foo f = (Foo) context.getBean("foo");
        f.printBar();
        f.printBaz();

        System.out.println(PropertyEditorManager.findEditor(Integer.class));
        
        
        System.out.println("Search path");
        for(String searchPath : PropertyEditorManager.getEditorSearchPath()) {
            System.out.println(searchPath);
        }

        System.out.println("---- list of all beans");
        for (String beanName : context.getBeanDefinitionNames()) {
            System.out.println(beanName);

        }
    }
}
