/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@SpringBootApplication
public class MyApplication {

	@RequestMapping("/")
	String home() {
		return "Hello World!";
	}

	@RequestMapping("/delay")
	String delay(@RequestParam("seconds") int seconds) throws InterruptedException {
		Thread.sleep(seconds * 1000);
		return "delayed";
	}

	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}
}