/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.sql.DataSource;

import com.mysql.cj.jdbc.MysqlDataSource;

public class App {

    public static DataSource createDataSource() {
        String dbUrl = "jdbc:mysql://localhost:3306/users";
        String dbUser = "yoav";
        String dbPassword = "yoav";

        MysqlDataSource mysqlDS = null;
        
        mysqlDS = new MysqlDataSource();
        mysqlDS.setURL(dbUrl);
        mysqlDS.setUser(dbUser);
        mysqlDS.setPassword(dbPassword);

        return mysqlDS;
        
    }

    public static void main(String[] args)  {
        try(Connection conn = createDataSource().getConnection()) {
            try(PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM users WHERE id = ?")) {
                pstmt.setInt(1, 1);
                ResultSet rs = pstmt.executeQuery();
                while(rs.next()) {
                    System.out.println(rs.getString("name"));
                }
            }
            
        } catch(SQLException e) {
            System.out.println("SQL Exception!");
            System.out.println(e);
        }
    }
}
