/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import com.example.business.service.MessageService;


@Controller
public class HomeController {
    
    @Autowired
    ApplicationContext context;

    @Autowired
    MessageService messageService;

    @RequestMapping("/")
    public String sayHello(Model model, @AuthenticationPrincipal Object user, Authentication authentication) {
        
        OAuth2User oauth2user = (OAuth2User)user;
        for(String key : oauth2user.getAttributes().keySet()) {
            System.out.println(key + ": " + oauth2user.getAttributes().get(key));
        }
        model.addAttribute("userid", oauth2user.getAttributes().get("sub"));
        
        return "index"; // This corresponds to the view name
    }
   
}