/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import  org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.userdetails.User;


@Controller
public class HomeController {
    @RequestMapping("/")
    public String sayHello(Model model, @AuthenticationPrincipal Object user) {
        
        if(user instanceof OAuth2User) {
            OAuth2User oauth2user = (OAuth2User)user;
            for(String key : oauth2user.getAttributes().keySet()) {
                System.out.println(key + ": " + oauth2user.getAttributes().get(key));
            }
    
            model.addAttribute("name", oauth2user.getAttribute("name"));
            model.addAttribute("pictureUrl", oauth2user.getAttribute("picture"));
        } else {
            User reguser = (User)user;
            model.addAttribute("name", reguser.getUsername());
        }
        return "index"; // This corresponds to the view name
    }
   
}