/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import java.util.Locale;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.context.MessageSource;
import org.springframework.context.support.ResourceBundleMessageSource;
import org.springframework.web.servlet.LocaleResolver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class MyController {

    @Autowired
    private MessageSource messageSource;

    @Autowired
    protected LocaleResolver localeResolver;

    @RequestMapping("/hello")
    public ResponseEntity<String> sayHello(Model model, HttpServletRequest request) {
        
        String body = this.messageSource.getMessage("hello", null, localeResolver.resolveLocale(request));
        return ResponseEntity.ok().body(body);
        
    }

}