/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public void messyMethod() throws MyException {
        throw new MyException();
    }

    public static void main(String[] args) {
        
    }
}
