/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class MyController {

    @RequestMapping("/hello")
    public String sayHello(Model model, @RequestParam("name") String name) {
        model.addAttribute("name", name);
        return "hellopage"; // This corresponds to the view name
    }
}