/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class App {
    private static final Logger LOGGER = LogManager.getLogger();

    private static void testExceptions() {
        try {   
            throw new Exception("Problem dude");
        } catch(Exception e) {
            LOGGER.error("Error: ", e);
        }
    }
    
    public static void main(String[] args) {
        
        LOGGER.warn("This value is too high: {}", 250);


        testExceptions();
    }
}
