/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.security.core.Authentication;

import com.example.security.GoogleAuthentication;
import com.example.security.GoogleIdentityDetails;

@Controller
public class HomeController {
    @RequestMapping("/")
    public String sayHello(Model model, Authentication authentication) {

        GoogleAuthentication googleAuth = (GoogleAuthentication)authentication;
        GoogleIdentityDetails googleIdentity = (GoogleIdentityDetails)googleAuth.getDetails();
        model.addAttribute("name", googleIdentity.getName());
        model.addAttribute("pictureUrl", googleIdentity.getPictureUrl());
        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/login/google-sign-in")
    public String googleSignIn() {
        return "google-sign-in";

    }

    @RequestMapping("/test")
    public String test() {
        return "index";
    }
   
}