/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.SQLException;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
    
    public static void main(String[] args) throws SQLException {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);

        UsersDAO dao = (UsersDAO)context.getBean("usersDAO");
        
        User john = new User(5, "John");
        
        dao.insertUser(john);
        dao.insertUser(john);
    }
}