/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jackson;

import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.LocalDate;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;


public class App {

    public static void readValue() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
        Person yoav = objectMapper.readValue(new File("person.json"), Person.class);

        System.out.println(yoav.getName());
        System.out.println(yoav.getTime());
    }

    public static void writeValue() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
        Person avi = new Person("Avi", 23, LocalDateTime.now());
        objectMapper.writeValue(new File("person.json"), avi);
        /* objectMapper.writeValue(System.out, avi); */
    }

    public static void main(String[] args) throws IOException {
        
        /* writeValue(); */
        readValue();
    }
}
