/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    
    public static void main(String[] args) throws IOException {
        
        ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");
        HelloWorld obj = (HelloWorld) context.getBean("helloWorld");
        obj.getMessage();

        InputStream stream = context.getResource("somefile.txt").getInputStream();
        BufferedReader reader = new BufferedReader(new InputStreamReader(stream));
        System.out.println(reader.readLine());
        
    }
}
