/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

@Controller
public class HomeController {
    @RequestMapping("/")
    public String sayHello(Model model) {
        model.addAttribute("name", "Yaffa");
        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/addUser")
    public String addUser(Model model, RedirectAttributes redirect) {
        redirect.addAttribute("userName", "Josh");
        // model.addAttribute("userName", "Yehoshua");

        return "redirect:/userAdded";
    }

    @RequestMapping("/userAdded")
    public String addUser() {
        
        return "user-added";
    }
   
}