/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import java.util.Set;
import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ModelAttribute;

import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;


@Controller
public class MyController {


    @RequestMapping("/")
    public String home(Model model) {
        PersonDto dto = new PersonDto();
        for(int i = 0; i < 3; ++i) {
            dto.addPerson(new Person());
        }
        model.addAttribute("dto", dto);

        return "index"; // This corresponds to the view name
    }

    @PostMapping("/person") 
    public String postPerson(@Validated @ModelAttribute("dto") PersonDto dto, BindingResult result) {
        if(result.hasErrors()) {
            return "index";
        }
        return "persons";
    }
}