/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import com.example.business.Role;
import com.example.business.User;

@Controller
public class HomeController {
    int counter = 0;
    private final List<SseEmitter> emitters = new CopyOnWriteArrayList<>();

    @RequestMapping("/")
    public String sayHello(Model model) {
        model.addAttribute("name", "Yaffa");
        return "index"; // This corresponds to the view name
    }

    @PostMapping("/chat")
    public ResponseEntity message(@RequestParam("message") String message) {
        System.out.println("RECEIVED MESSAGE");
        List<SseEmitter> deadEmitters = new ArrayList<>();
        System.out.println(emitters.size() + " Number of emitters");
        counter++;
        emitters.forEach(emitter -> {
            try {
                User user = new User();
                user.setId("1a2b3c");
                user.setName("Zohran");
                user.setAge(30);
                user.setRole(Role.ADMIN);
                emitter.send(SseEmitter.event().id(String.format("%d", counter)).name("CHAT").data(user));
                /* emitter.complete(); */
            } catch (Exception e) {
                System.out.println(e.getCause());
                System.out.println(e.toString());
                /* deadEmitters.add(emitter); */
            }
        });
        emitters.removeAll(deadEmitters);

        return new ResponseEntity(HttpStatus.OK);
    }

    @GetMapping(path="/chat", produces=MediaType.TEXT_EVENT_STREAM_VALUE)
    public SseEmitter chatRegister() {
        System.out.println("NEW EMITTER");
        SseEmitter emitter = new SseEmitter();
        emitters.add(emitter);
        emitter.onCompletion(() -> { emitters.remove(emitter); System.out.println("COMPLETED"); } );
        emitter.onTimeout(() -> emitters.remove(emitter));
        emitter.onError((e) ->  { System.out.println("ERROR: " + e);  emitters.remove(emitter); });

        return emitter;
    }
}