/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping("/api")
public class RedirectController {

    @GetMapping("/google")
    public String redirectToExternalUrl() {
        // Redirect to an external URL
        return "redirect:https://www.google.com";
    }

    @GetMapping("/home")
    public String redirectToInternalUrl() {
        // Redirect to another internal controller method
        return "redirect:/api/welcome";
    }

    @GetMapping("/welcome")
    public String welcome() {
        // Return a view name
        return "welcome";
    }
}