/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import my.spring.child.ChildAppConfig;
import my.spring.child.HTTPServer;
import my.spring.parent.ParentAppConfig;


public class App {
    
    public static void main(String[] args) {
        
        AnnotationConfigApplicationContext parentContext = new AnnotationConfigApplicationContext();
        AnnotationConfigApplicationContext childContext = new AnnotationConfigApplicationContext();
        // we need to set parent before loading the @Configuration classes
        childContext.setParent(parentContext);
        // now register the @Configuration classes
        parentContext.register(ParentAppConfig.class);
        childContext.register(ChildAppConfig.class);
        parentContext.refresh();
        childContext.refresh();

        HTTPServer obj = (HTTPServer) childContext.getBean("httpServer");
        obj.sendMessage();
    }
}
