/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import java.util.Set;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ModelAttribute;

import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;


@Controller
public class MyController {

    @ModelAttribute
    Person populatePerson() {
        return new Person();
    }


    @RequestMapping("/")
    public String sayHello(Model model) {
        model.addAttribute("name", "Yaffa");
        return "index"; // This corresponds to the view name
    }

    @PostMapping("/person") 
    public String postPerson(@Validated Person person, BindingResult result) {
        if(result.hasErrors()) {
            return "index";
        }
        return "person";
    }
}