/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.Authentication;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.beans.factory.annotation.Autowired;

import com.example.business.exception.UserAlreadyInTenantException;
import com.example.business.service.TenantService;

import com.example.helpers.Constants;

@Controller
@RequestMapping("/tenant")
public class TenantController {
    @Autowired
    TenantService tenantService;

    @PostMapping("/create")
    public String createTenant(@AuthenticationPrincipal Object user, @RequestParam("name") String tenantName) {
        OAuth2User oauth2User = (OAuth2User)user;
        String id = oauth2User.getAttribute("sub");
        tenantService.createTenant(tenantName, id);

        return "redirect:/";
    }

    @PostMapping("/join")
    public String joinTenant(@AuthenticationPrincipal Object user, @RequestParam("id") String tenantId) {
        OAuth2User oauth2User = (OAuth2User)user;
        String userId = oauth2User.getAttribute("sub");
        try {
            tenantService.joinToTenant(tenantId, userId);
        } catch(UserAlreadyInTenantException e) {
            return "user-already-in-tenant";
        }

        return "redirect:/";
    }

    @GetMapping("/connect") 
    public String connectToTenant(@AuthenticationPrincipal Object user, 
            @RequestParam("tenantId") String tenantId, 
            HttpServletResponse response) {
        
        OAuth2User oauth2User = (OAuth2User)user;
        String userId = oauth2User.getAttribute("sub");

        if (tenantService.isUserPartOfTenant(userId, tenantId)) {
            System.out.println("SETTING COOKIE");
            Cookie tenantCookie = new Cookie(Constants.TENANT_COOKIE_NAME, tenantId);
            tenantCookie.setPath("/");
            response.addCookie(tenantCookie);
        } else {
            System.out.println("NOT GOOD");
            // return 403
        }

        return "redirect:/home";
    }
   
}