/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

@Controller
public class EmailController {

    @Autowired
    private EmailFormValidator emailFormValidator;

    @GetMapping("/email")
    public String showForm(Model model) {
        model.addAttribute("emailForm", new EmailForm());
        return "emailForm";
    }

    @PostMapping("/email")
    public String submitForm(@ModelAttribute("emailForm") EmailForm emailForm, BindingResult bindingResult) {
        emailFormValidator.validate(emailForm, bindingResult);
        if (bindingResult.hasErrors()) {
            return "emailForm";
        }
        return "success";
    }
}