/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.testng.Assert.assertNotNull;
import org.testng.annotations.Test;

public class AnotherTest {
    @Test public void sayHi() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
