/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class MyController {

    @RequestMapping("/hello")
    public String hello(Model model) {
        model.addAttribute("message", "Hello, Spring MVC! This is using AbstractDispatcherServletInitializer.");
        return "/WEB-INF/hello.jsp"; // This corresponds to the view name
    }
}