/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yoav;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        assertTrue(true);
    }
}
