/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc.web;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class WebController {
    @RequestMapping("/hello")
    public String sayHello(Model model) {
        model.addAttribute("name", "Yaffa");
        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/allUsers")
    public String getAllUsers(Model model) {
        model.addAttribute()
    }
}