/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import java.io.IOException;
import java.util.Map;
import java.util.HashMap;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class MyController {

    @RequestMapping("/hello")
    public String sayHello(Model model) throws IOException {
        model.addAttribute("message", "Hello, Spring MVC!");

        if(1 == 1) { throw new IOException(); }
        return "hellopage"; // This corresponds to the view name
    }

    // demonstrates the usage of ResponseStatusExceptionResolver, which resolves exceptions that are annotated
    // with ResponseStatus
    @RequestMapping("/badboy")
    public String badBoy(Model model) throws BadRequestException {
        throw new BadRequestException();
    }


    // demonstrates the usage of ExceptionHandlerExceptionResolver
    // NOTE: the MyCustomException also annotated with @ResponseStatus
    // but since ExceptionHandlerExceptionResolver is in higher priority, 
    // it is used

    @RequestMapping("/banana")
    public String banana(Model model) throws MyCustomException {
        throw new MyCustomException();
    }

    @ExceptionHandler
    public ModelAndView bananaHandler(MyCustomException e) {
        Map<String,String> model = new HashMap<>();
        model.put("color", "Yellow");
        model.put("size", "Large");
        return new ModelAndView("banana", model);
    }
}