/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.security.oauth2.core.user.OAuth2User;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;

import com.example.business.model.Product;
import com.example.business.service.TenantService;
import com.example.helpers.TenantContext;

//import com.example.business.model.Product;
import com.example.web.forms.ProductDto;
import com.example.business.service.ProductService;
import com.example.business.service.UserService;

@Controller
public class HomeController {
    
    @Autowired
    TenantService tenantService;

    @Autowired
    UserService userService;

    @Autowired
    ProductService productService;

    @ModelAttribute("user")
    public void addUserToModel(Model model, @AuthenticationPrincipal Object user) {
        OAuth2User oauth2User = (OAuth2User)user;
        model.addAttribute("user", userService.getUserById(oauth2User.getAttribute("sub")).get());
    }

    @RequestMapping("/")
    public String sayHello(Model model, @AuthenticationPrincipal Object user) {
        OAuth2User oauth2user = (OAuth2User)user;
        model.addAttribute("name", oauth2user.getAttribute("name"));
        
        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/home")
    public String tenantHome(Model model) {
        List<Product> allProducts = productService.getAllProducts();

        model.addAttribute("allProducts", allProducts);
        model.addAttribute("currentTenant", TenantContext.getCurrentTenantId());
        model.addAttribute("product", new ProductDto());
        
        return "home";
    }

    @PostMapping("/product/add")
    public String addProduct(ProductDto p) {
        productService.addProduct(p);

        return "redirect:/home";
    }

    @GetMapping("/my-tenants")
    public String getTenants(Model model, @AuthenticationPrincipal Object user) {
        OAuth2User oauth2User = (OAuth2User)user;
        model.addAttribute("tenants", tenantService.getAllTenantsForUser(oauth2User.getAttribute("sub")));
        model.addAttribute("invitations", userService.getAllInvitationsForUser(oauth2User.getAttribute("sub")));
        

        return "my-tenants";
    }
   
}