/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.security.core.Authentication;


@Controller
public class HomeController {
    @RequestMapping("/")
    public String sayHello(Model model, Authentication authentication) {

        return "index"; // This corresponds to the view name
    }

    @RequestMapping("/login")
    public String login() {
        return "login";

    }

    @RequestMapping("/test")
    public String test() {
        return "index";
    }
   
}