/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;

 import com.sun.net.httpserver.HttpServer;

import io.micrometer.core.instrument.observation.DefaultMeterObservationHandler;
import io.micrometer.observation.Observation;
import io.micrometer.observation.ObservationRegistry;
import io.micrometer.prometheusmetrics.PrometheusConfig;
import io.micrometer.prometheusmetrics.PrometheusMeterRegistry;

public class App {
    public static void main(String[] args) throws IOException {
        // creating a registry
        ObservationRegistry registry = ObservationRegistry.create();

        // add metrics registry
        PrometheusMeterRegistry meterRegistry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);

        // adding the SimpleObservationHandler to the registry
        registry.observationConfig().observationHandler(new SimpleObservationHandler());
        // adding the DefaultMeterObservationRegistry
        registry.observationConfig().observationHandler(new DefaultMeterObservationHandler(meterRegistry));

        HttpServer server = HttpServer.create(new InetSocketAddress(8082), 0);

        server.createContext("/ping", exchange -> {
        try {
            // creating an Observation named 'foo'
            Observation observation = Observation.createNotStarted("foo", registry)
                .lowCardinalityKeyValue("lowTag", "lowTagValue")
                .highCardinalityKeyValue("highTag", "highTagValue");
            observation.observe(() -> {
                observation.event(Observation.Event.of("event1"));
                System.out.println("Hello");
            });
            byte[] body = "pong\n".getBytes(StandardCharsets.UTF_8);
            exchange.sendResponseHeaders(200, body.length);
            exchange.getResponseBody().write(body);
        } finally {
            exchange.close();
        }
        });

        server.createContext("/metrics", exchange -> {
            // Render Micrometer metrics in Prometheus plaintext format
            String scrape = meterRegistry.scrape();
            byte[] body = scrape.getBytes(StandardCharsets.UTF_8);
            exchange.getResponseHeaders().add("Content-Type", "text/plain; version=0.0.4; charset=utf-8");
            exchange.sendResponseHeaders(200, body.length);
            exchange.getResponseBody().write(body);
            exchange.close();
        });

        server.start();
        System.out.println("Up! /ping and /metrics on http://localhost:8080");
    }
}
