/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

import org.example.model.User;
import org.example.service.TransactionService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        TransactionService transactionService = (TransactionService)context.getBean(TransactionService.class);

        List<User> users = transactionService.getAllUsers();
        for(User user : users) {
            System.out.println(user.getName());
        }
        
    }
}
