/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

import org.example.model.Account;
import org.example.model.Transaction;
import org.example.service.TransactionService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        TransactionService transactionService = (TransactionService)context.getBean(TransactionService.class);

        List<Account> accounts = transactionService.getAllAccounts();
        for(Account account : accounts) {
            System.out.println(account);
        }

        transactionService.transfer(1, 2, 100);

        accounts = transactionService.getAllAccounts();
        for(Account account : accounts) {
            System.out.println(account);
        }

        for(Transaction t : transactionService.getAllTransactions()) {
            System.out.println(t);
        }
        
    }
}
