/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.spring;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    
    public static void main(String[] args) {
        
        ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");
        HTTPServer obj = (HTTPServer) context.getBean("http");
        obj.sendMessage();
    }
}
