/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.springframework.web.client.RestClient;

public class App {
    public static void get() {
        RestClient rest = RestClient.builder().build();

        Post resp = rest.get().uri("https://jsonplaceholder.typicode.com/posts/1").retrieve().body(Post.class);
        System.out.println(resp);
    }

    public static void main(String[] args) {
        get();
    }
}
