/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ModelAttribute;

@Controller
public class MyController {

    @ModelAttribute("fullList")
    public ListForm fullList() {
        return new ListForm();
    }

    @RequestMapping("/")
    public String sayHello(Model model) {
        return "index"; // This corresponds to the view name
    }

    @PostMapping("/update")
    public String update(ListForm form) {
        form.print();
        return "redirect:/";
    }
   
}