/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.Collections;

import com.sun.net.httpserver.HttpServer;

import io.micrometer.observation.Observation;
import io.micrometer.observation.ObservationRegistry;
import io.micrometer.observation.ObservationHandler;

import io.micrometer.tracing.handler.DefaultTracingObservationHandler;
import io.micrometer.tracing.handler.PropagatingSenderTracingObservationHandler;
import io.micrometer.tracing.handler.PropagatingReceiverTracingObservationHandler;
import io.micrometer.tracing.otel.bridge.OtelCurrentTraceContext;
import io.micrometer.tracing.otel.bridge.OtelTracer;
import io.micrometer.tracing.otel.bridge.OtelPropagator;


import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.api.trace.Tracer;

public class App {
    public static void main(String[] args) throws IOException {
        
        OpenTelemetry otel = Otel.initOpenTelemetry();
        Tracer otelTracer = otel.getTracer("my-tracer");

        OtelCurrentTraceContext otelCurrentTraceContext = new OtelCurrentTraceContext();

        OtelTracer tracer = new OtelTracer(otelTracer, otelCurrentTraceContext, event -> {});

        OtelPropagator propagator = new OtelPropagator(otel.getPropagators() ,otelTracer);

        // creating a registry
        ObservationRegistry registry = ObservationRegistry.create();

        // adding the SimpleObservationHandler to the registry
        registry.observationConfig().observationHandler(new ObservationHandler.FirstMatchingCompositeObservationHandler(
            new PropagatingSenderTracingObservationHandler<>(tracer, propagator),
            new PropagatingReceiverTracingObservationHandler<>(tracer, propagator),
            new DefaultTracingObservationHandler(tracer)));
        

        HttpServer server = HttpServer.create(new InetSocketAddress(8082), 0);

        server.createContext("/ping", exchange -> {
        try {
            // creating an Observation named 'foo'
            Observation observation = Observation.createNotStarted("foo", registry)
                .lowCardinalityKeyValue("lowTag", "lowTagValue")
                .highCardinalityKeyValue("highTag", "highTagValue");
            observation.observe(() -> {
                observation.event(Observation.Event.of("event1"));
                System.out.println("Hello");
            });
            byte[] body = "pong\n".getBytes(StandardCharsets.UTF_8);
            exchange.sendResponseHeaders(200, body.length);
            exchange.getResponseBody().write(body);
        } finally {
            exchange.close();
        }
        });

        server.start();
        System.out.println("Up! /ping and /metrics on http://localhost:8080");
    }
}
