/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

import java.beans.PropertyEditorSupport;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.WebDataBinder;

import org.springframework.validation.BindingResult;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.InitBinder;


@Controller
public class WebController {

    /* full list for Map<Category, List<ListItem>> */
    @ModelAttribute("fullList")
    public ProductDto fullList() {
        ProductDto form = new ProductDto();

        Map<Category, List<Product>> map = new HashMap<>();

        List<Product> vegetables = new ArrayList<>();
        vegetables.add(new Product("Cucumber"));
        vegetables.add(new Product("Tomato"));
        map.put(Category.VEGETABLES, vegetables);

        List<Product> fruit = new ArrayList<>();
        fruit.add(new Product("Orange"));
        fruit.add(new Product("Strawberry"));
        map.put(Category.FRUITS, fruit);

        form.setList(map);
        return form;
    }


    @RequestMapping("/")
    public String home() {
        return "index"; // This corresponds to the view name
    }

    @PostMapping("/update")
    public String update(@ModelAttribute("fullList") ProductDto form, BindingResult result) {
        if(result.hasErrors()) {
            System.out.println("ERRORRS");
            return "index";
        }
        form.print();
        return "index";
    }

}